Parameters:
  MyKeyPairName:
    Type: String
  MyImageId:
    Type: String
  VpcId:
    Type: String  
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref MyKeyPairName
      InstanceType: t2.micro
      SecurityGroupIds:
         -  !Ref MySecurityGroup
      ImageId: !Ref MyImageId
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allowing SSH from everywhere
      SecurityGroupIngress:
        IpProtocol: tcp
        ToPort: 22
        FromPort: 22
        CidrIp: '0.0.0.0/0'


